### ISSUE TITLE
Background research

### ISSUE THREAD

**Issue by Nicanor008** [Nicanor008/js-messaging#1]
We need to understand the requirements of what is needed to build a complete Messaging system from the ground up to completion. Do research on the background and requirements to develop this

**Comment by Nicholas-Kipkoech** [comment]
Noted. This can work around cron-job

**Comment by Nicanor008** [comment]
cron jobs are tricky since they are specific schedule

**Comment by Nicanor008** [comment]
am thinking of something like a queue data structure  such that each app creates its own queue that consumes the current one waiting for it to be completed then start the next one until there's nothing on the queue

**Comment by Nicholas-Kipkoech** [comment]
> am thinking of something like a queue data structure such that each app creates its own queue that consumes the current one waiting for it to be completed then start the next one until there's nothing on the queue

This can work, so we need to figure out when the request has been completed successfully

**Comment by Nicanor008** [comment]
> > am thinking of something like a queue data structure such that each app creates its own queue that consumes the current one waiting for it to be completed then start the next one until there's nothing on the queue
> 
> This can work, so we need to figure out when the request has been completed successfully

Phases/Steps of use by any project: 
- Initialise the queue :- this creates a new queue data structure for the project
- Use - this involves managing the queue, adding and removing items in queue. The queue will remain empty if not used
- destroy - only destroy the queue of deleting/destroying the initialization

**Comment by Nicanor008** [comment]
Architecture:
- Message broker - handles message flow between producers and consumers
- Queues - hold messages, we can use enqueue and dequeue operations
- Exchange - routes messages to queues based on certain rules
- Bindings - defines how messages should be routed
- Producers & Consumers - send and receive message


Implementation Tools:
- TypeScript
- NodeJS
- Redis- storage for Queues, although MongoDB might also be good
- WebSockets/HTTP

@Nicholas-Kipkoech what do you think?

**Comment by Nicholas-Kipkoech** [comment]
> Architecture:
> 
> * Message broker - handles message flow between producers and consumers
> * Queues - hold messages, we can use enqueue and dequeue operations
> * Exchange - routes messages to queues based on certain rules
> * Bindings - defines how messages should be routed
> * Producers & Consumers - send and receive message
> 
> Implementation Tools:
> 
> * TypeScript
> * NodeJS
> * Redis- storage for Queues, although MongoDB might also be good
> * WebSockets/HTTP
> 
> @Nicholas-Kipkoech what do you think?

This is good, I didn't of storage upto now, so we also need to store queues right? I think Redis can work since a user can install it on their machine or even on their server.

**Comment by Nicholas-Kipkoech** [comment]
Can we have a call tomorrow at 10:00 am? We can plan on how we be working on this?

**Comment by Nicanor008** [comment]
lunchtime, 1:30 - 2pm tomorrow is fine
