### ISSUE TITLE
Queues

### ISSUE THREAD

**Issue by Nicanor008** [Nicanor008/js-messaging#3]
- enqueue - add item
- dequeue - remove first item in queue
- isEmpty - check if queue is empty
- peek - check specific item

**Comment by Nicholas-Kipkoech** [comment]
@Nicanor008  I pushed the changes for this issue by mistake without creating a branch for it but is fine now, can you setup typescript because it wont run any .ts files

**Comment by Nicanor008** [comment]
Now that we've the basic stuff up and running, can you test out your functionality @Nicholas-Kipkoech
